version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: api-vote
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/app
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - db